name: base_project
description: A new Flutter project.
publish_to: 'none' 
version: 1.1.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^12.0.1
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  table_calendar: ^3.0.9
  http: any
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  dio: ^5.3.4
  collection: ^1.17.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - resources/images/
  fonts:
   - family: Roboto
     fonts:
      - asset: fonts/Roboto-Light.ttf